module.exports = {
    BASE_URL: 'https://api.pubg.com',

    DEFAULT_SHARD: 'pc-oc',

    SHARDS: [
        'kakao',
        'psn',
        'steam',
        'tournament',
        'xbox',
        'pc-as',
        'pc-eu',
        'pc-jp',
        'pc-kakao',
        'pc-krjp',
        'pc-na',
        'pc-oc',
        'pc-ru',
        'pc-sa',
        'pc-sea',
        'pc-tournament',
        'psn-as',
        'psn-eu',
        'psn-na',
        'psn-oc',
        'xbox-as',
        'xbox-eu',
        'xbox-na',
        'xbox-oc',
        'xbox-sa',
    ],
};
